#
# We like long lines, 120 characters:
#
Layout/LineLength:
  Max: 120

#
# Disable most metrics, as we don't want to change the code to satisfy
# them, at least not now.
#
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SafeNavigation:
  Enabled: false

#
# The preferred way to indent long chains of method calls in this
# project is the following:
#
#   @connection.system_service
#     .vms_service
#     .vm_service(123)
#     .disk_attachments_service
#     .attachment_service(456)
#
# But Rubocop by default wants this:
#
#   @connection.system_service
#              .vms_service
#              .vm_service(123)
#              .disk_attachments_service
#              .attachment_service(456)
#
# This parameter adjusts it to the policy of the project.
#
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

#
# We don't like to use conditional assigments.
#
Style/ConditionalAssignment:
  Enabled: false

#
# We need to use `DateTime` instead of `Date` or `Time` because we use
# the `xmlschema` method, which is only included in `DateTime`.
#
Style/DateTime:
  Enabled: false

#
# The spec for types includes some apparently stupid tests, like
# checking that the result of `==` is `true` when an object is compared
# to itself. Rubocop doesn't like these tests, but we want them anyhow,
# so we exclude that spec.
#
Lint/BinaryOperatorWithIdenticalOperands:
  Exclude:
    - 'spec/type_spec.rb'
Style/NilComparison:
  Exclude:
    - 'spec/type_spec.rb'

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

#
# Exclude the generated source code and temporary files, as it isn't
# practical to enforce style there (too many long lines, etc).
#
AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'ext/ovirtsdk4c/extconf.rb'
    - 'lib/ovirtsdk4/readers.rb'
    - 'lib/ovirtsdk4/services.rb'
    - 'lib/ovirtsdk4/types.rb'
    - 'lib/ovirtsdk4/writers.rb'
    - 'lib/ovirtsdk4/version.rb'
    - 'pkg/**/*'
    - 'tmp/**/*'

#
# This things used to work fine before upgrading Rubocop, and we don't want
# to address them now. At some point we should remove these lines, check the
# result and fix the code accordingly.
#
Style/RedundantFileExtensionInRequire:
  Enabled: False
Style/OptionalBooleanParameter:
  Enabled: False
Naming/VariableNumber:
  Enabled: False
Style/AccessorGrouping:
  Enabled: False
Style/SingleArgumentDig:
  Enabled: False
Style/ZeroLengthPredicate:
  Enabled: False
