#!/usr/bin/ruby

#
# Copyright (c) 2015-2016 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require 'rake'
require 'rake/extensiontask'
require 'rspec/core/rake_task'
require 'rubocop/rake_task'
require 'rubygems'
require 'rubygems/package_task'

# The names of the gem and the extension:
GEM_NAME = 'ovirt-engine-sdk'.freeze
EXT_NAME = 'ovirtsdk4c'.freeze

# Load the gem specification:
spec = Gem::Specification.load("#{GEM_NAME}.gemspec")

# Add the compilation task:
Rake::ExtensionTask.new(EXT_NAME, spec)

# Task to run RSpec:
RSpec::Core::RakeTask.new(:rspec) do |test|
  test.pattern = 'spec/**/*_spec.rb'
end

# Task to run Rubocop:
RuboCop::RakeTask.new(:rubocop)

# Task to run RSpec and Rubocop:
task test: [:rspec, :rubocop]

# Add the gem packaging task:
Gem::PackageTask.new(spec) do |pkg|
end

# In order to run the tests the extension needs to be compiler first:
task test: :compile
